services:
  spacecraft-viz:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=3.3
      - MESA_GLSL_VERSION_OVERRIDE=330
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - VTK_RENDERER=MESA
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true